# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ming Jie See
tagline:          'Machine Learning, Embedded Systems, FPGAs.'
description:      'Maker, engineer, tinkerer. Enjoy working with tech and pushing the envelope.'
url:              https://jeremysee2.github.io/
baseurl:          /
repository:       jeremysee2/jeremysee4.github.io

author:
  name:           'Ming Jie See'

gem: [jekyll-paginate, jekyll-gists]

plugins:
  - jekyll-paginate
paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jeremysee2/jeremysee4.github.io
